// Decompiled with JetBrains decompiler
// Type: Elements.eMovieType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 81CDCA9F-D99D-4BB7-B092-3FE4B4616CF6
// Assembly location: D:\PCRCalculator\解包数据\逆向dll\Assembly-CSharp.dll

namespace Elements
{
  public enum eMovieType
  {
    NONE,
    VIEW_SPLASH,
    VIEW_TITLE,
    VIEW_TITLE_CUSTOMIZE,
    VIEW_STORY,
    VIEW_STORY_CUSTOMIZE,
    VIEW_STORY_CHAPTER,
    VIEW_QUEST,
    VIEW_QUEST_CUSTOMIZE,
    VIEW_GACHA_START_PRINCESS_FES,
    VIEW_GACHA_RETURN_USER_PRINCESS_FES,
    VIEW_GACHA_ANNIVERSARY,
    VIEW_GACHA_PICKUP,
    VIEW_GACHA_PLATINUM,
    VIEW_GACHA_NORMAL,
    VIEW_GACHA_TUTORIAL,
    VIEW_GACHA_SPECIAL,
    VIEW_GACHA_PRIZE,
    VIEW_GACHA_ANIMATION,
    VIEW_GACHA_ANIMATION_SP,
    CUT_IN,
    STORY,
    NEWCHARACTER_INTRODUCTION,
    NEWCHARACTER_INTRODUCTION_NONE_LOOP,
    EVENT,
    CHARACTER,
    VOTE_TOP,
    VOTE_RESULT,
    ARCADE,
    PRINCESS_FORM_SKILL_NORMAL,
    PRINCESS_FORM_SKILL_SHADOW,
    PRINCESS_FORM_SKILL_NORMAL_4X,
    PRINCESS_FORM_SKILL_SHADOW_4X,
  }
}
