// Decompiled with JetBrains decompiler
// Type: Elements.PriorityPattern
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 81CDCA9F-D99D-4BB7-B092-3FE4B4616CF6
// Assembly location: D:\PCRCalculator\解包数据\逆向dll\Assembly-CSharp.dll

namespace Elements
{
  public enum PriorityPattern
  {
		NONE = 1,
		RANDOM,
		NEAR,
		FAR,
		HP_ASC,
		HP_DEC,
		OWNER,
		RANDOM_ONCE,
		FORWARD,
		BACK,
		ABSOLUTE_POSITION,
		ENERGY_DEC,
		ENERGY_ASC,
		ATK_DEC,
		ATK_ASC,
		MAGIC_STR_DEC,
		MAGIC_STR_ASC,
		SUMMON,
		ENERGY_REDUCING,
		ATK_PHYSICS,
		ATK_MAGIC,
		ALL_SUMMON_RANDOM,
		OWN_SUMMON_RANDOM,
		BOSS,
		HP_ASC_NEAR,
		HP_DEC_NEAR,
		ENERGY_DEC_NEAR,
		ENERGY_ASC_NEAR,
		ATK_DEC_NEAR,
		ATK_ASC_NEAR,
		MAGIC_STR_DEC_NEAR,
		MAGIC_STR_ASC_NEAR,
		SHADOW,
		NEAR_MY_TEAM_WITHOUT_OWNER,
		HP_VALUE_DEC_NEAR_FORWARD,
		HP_VALUE_ASC_NEAR_FORWARD,
		ENERGY_DEC_NEAR_MAX_FORWARD,
		PHYSICS_OR_MAGIC_HIGH_ATTACK_DEC,
		PHYSICS_OR_MAGIC_HIGH_ATTACK_ASC,
		ALL_ENEMY_INCLUDE_STEALTH,
		ENERGY_ASC_BACK_WITHOUT_OWNER,
		PARENT_TARGET_PARTS
	}
}
